spring:
  h2:
    console:
      enabled: true
togglz:
  features:
    DISCOUNT_APPLIED:
      enabled: true
  console:
    secured: false
management:
  endpoints:
    web:
      exposure:
        include: 'togglz'
